### ISSUE TITLE
What's Chai ?

### ISSUE THREAD

**Issue by ijogendrajat** [hiteshchoudhary/open-source-contribution#133]
*Chai* is a word for [tea](https://en.wikipedia.org/wiki/Tea) in numerous languages and *Tea* is an aromatic [beverage](https://en.wikipedia.org/wiki/Drink) prepared by pouring hot or [boiling water](https://en.wikipedia.org/wiki/Boiling_water) over [cured](https://en.wikipedia.org/wiki/Curing_(vegetable_preservation)) or fresh leaves of [Camellia sinensis](https://en.wikipedia.org/wiki/Camellia_sinensis), an [evergreen](https://en.wikipedia.org/wiki/Evergreen) [shrub](https://en.wikipedia.org/wiki/Shrub) native to East Asia which probably originated in the borderlands of [southwestern China](https://en.wikipedia.org/wiki/Southwest_China) and [northern Myanmar](https://en.wikipedia.org/wiki/Geography_of_Myanmar).

**Comment by ijogendrajat** [comment]
Now you can translate the above text into many languages yourself and become a valuable contributor to open source projects. Thank you for your future contributions!

**Comment by flyingcakes85** [comment]
🍵

**Comment by adasarpan404** [comment]
☕

**Comment by pradyumnapanda07** [comment]
zindagi

**Comment by sanika365** [comment]
Coding with chai☕

**Comment by adasarpan404** [comment]
you have a grammar mistake in issue title

**Comment by flyingcakes85** [comment]
> grammar mistake

the spirit of open source :muscle:

**Comment by ijogendrajat** [comment]
Grammar issue fixed in title guys 🥳

**Comment by ijogendrajat** [comment]
> you have a grammar mistake in issue title

Fixed
