### ISSUE TITLE
Offering jobs to anyone who gets their pull requests accepted

### ISSUE THREAD

**Issue by HACKE-RC** [hiteshchoudhary/open-source-contribution#25]
isi ke sapne dekh rahe the na?

**Comment by lav1shkumar** [comment]
yes sir, ab to meko 4cr ka package hona🤩

**Comment by HACKE-RC** [comment]
garib ho kya sir? 4 cr ka to mai baniyan pehenta

**Comment by lav1shkumar** [comment]
are sir meine to mazaak mein bol diya😌, phir offer letter when?
btw jokes apart, i was looking through your OS blog and it's very helpful, Thanks!
